### ISSUE TITLE
麻烦发一版composer稳定版本吧～

### ISSUE THREAD

**Issue by Rivsen** [simboss-sdk/simboss-php-sdk#1]
RT

**Comment by simboss-sdk** [comment]
我们已经上传过php版的composer包。
https://packagist.org/packages/simboss/sdk

**Comment by Rivsen** [comment]
我指的稳定版本是指不需要在引入的时候特别开启依赖不稳定开发版本开关，我写过一篇相关的稳定版本发布的文章可以参考参考～ [戳这里](https://rivsen.github.io/post/how-to-publish-package-to-packagist-using-github-and-composer-step-by-step#%E5%8C%85%E7%89%88%E6%9C%AC%E7%AE%A1%E7%90%86)

**Comment by qq805772847** [comment]
👌，细节之处没有注意到请见谅。谢谢指出，我们会尽早安排发布稳定版本。 Blog 赞一个。

**Comment by Rivsen** [comment]
客气客气，很多年前写的啦，有些操作可能有出入，有问题找我～
